import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import "./globals.css";

import Header from "@/components/header";
import { Raleway as Fonts } from "next/font/google";

const font = Fonts({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "School Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
        <meta name="theme-color" media="(prefers-color-scheme: light)" content="#f8f8f8" />
        <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#212529" />
      </head>
      <body className={cn("min-h-screen pt-20 lg:px-4 bg-[#f8f8f8] dark:bg-[#212529] antialiased", font.className)}>
        <Header />
        <main className="flex flex-col flex-wrap container mx-auto">{children}</main>
      </body>
    </html>
  );
}
